builds:
  - binary: goreleasertest
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: goreleasertest
    homepage: https://github.com/atileren/goreleasertest
    tap:
      owner: atileren
      name: homebrew-goreleasertest
    commit_author:
      name: atileren
      email: atil.eren@outlook.com

checksum:
  name_template: 'checksums.txt'
